 const products = [
    {
      id: 1,
      name: "Product 1",
      price: 10.99,
      quantity: 50,
      rating: 4.5,
      img: "https://example.com/product1.jpg",
    },
    {
      id: 2,
      name: "Product 2",
      price: 9.99,
      quantity: 100,
      rating: 4.0,
      img: "https://example.com/product2.jpg",
    },
    {
      id: 3,
      name: "Product 3",
      price: 12.99,
      quantity: 75,
      rating: 4.8,
      img: "https://example.com/product3.jpg",
    },
    {
      id: 4,
      name: "Product 4",
      price: 8.99,
      quantity: 200,
      rating: 3.5,
      img: "https://example.com/product4.jpg",
    },
    {
      id: 5,
      name: "Product 5",
      price: 15.99,
      quantity: 30,
      rating: 4.9,
      img: "https://example.com/product5.jpg",
    },
    {
      id: 6,
      name: "Product 6",
      price: 7.99,
      quantity: 150,
      rating: 3.0,
      img: "https://example.com/product6.jpg",
    },
    {
      id: 7,
      name: "Product 7",
      price: 11.99,
      quantity: 60,
      rating: 4.2,
      img: "https://example.com/product7.jpg",
    },
    {
      id: 8,
      name: "Product 8",
      price: 14.99,
      quantity: 25,
      rating: 4.7,
      img: "https://example.com/product8.jpg",
    },
    {
      id: 9,
      name: "Product 9",
      price: 6.99,
      quantity: 175,
      rating: 2.5,
      img: "https://example.com/product9.jpg",
    },
    {
      id: 10,
      name: "Product 10",
      price: 18.99,
      quantity: 20,
      rating: 4.3,
      img: "https://example.com/product10.jpg",
    },
    {
      id: 11,
      name: "Product 11",
      price: 5.99,
      quantity: 300,
      rating: 2.0,
      img: "https://example.com/product11.jpg",
    },
    {
      id: 12,
      name: "Product 12",
      price: 20.99,
      quantity: 15,
      rating: 4.6,
      img: "https://example.com/product12.jpg",
    },
    {
      id: 13,
      name: "Product 13",
      price: 8.49,
      quantity: 120,
      rating: 3.8,
      img: "https://example.com/product13.jpg",
    },
    {
      id: 14,
      name: "Product 14",
      price: 13.99,
      quantity: 40,
      rating: 4.4,
      img: "https://example.com/product14.jpg",
    },
    {
      id: 15,
      name: "Product 15",
      price: 11.49,
      quantity: 90,
      rating: 3.7,
      img: "https://example.com/product15.jpg",
    },
    {
      id: 16,
      name: "Product 16",
      price: 9.99,
      quantity: 80,
      rating: 4.1,
      img: "https://example.com/product16.jpg",
    },
    {
      id: 17,
      name: "Product 17",
      price: 16.99,
      quantity: 35,
      rating: 4.9,
      img: "https://example.com/product17.jpg",
    },
    {
      id: 18,
      name: "Product 18",
      price: 7.99,
      quantity: 200,
      rating: 3.3,
      img: "https://example.com/product18.jpg",
    },
    {
      id: 19,
      name: "Product 19",
      price: 19.99,
      quantity: 10,
      rating: 4.5,
      img: "https://example.com/product19.jpg",
    },
    {
      id: 20,
      name: "Product 20",
      price: 6.49,
      quantity: 250,
      rating: 2.8,
      img: "https://example.com/product20.jpg",
    },
    {
      id: 21,
      name: "Product 21",
      price: 12.99,
      quantity: 70,
      rating: 4.0,
      img: "https://example.com/product21.jpg",
    },
    {
      id: 22,
      name: "Product 22",
      price: 17.99,
      quantity: 25,
      rating: 4.7,
      img: "https://example.com/product22.jpg",
    },
    {
      id: 23,
      name: "Product 23",
      price: 8.99,
      quantity: 180,
      rating: 3.5,
      img: "https://example.com/product23.jpg",
    },
    {
      id: 24,
      name: "Product 24",
      price: 14.99,
      quantity: 45,
      rating: 4.3,
      img: "https://example.com/product24.jpg",
    },
    {
      id: 25,
      name: "Product 25",
      price: 10.49,
      quantity: 100,
      rating: 3.9,
      img: "https://example.com/product25.jpg",
    },
  ];
  export default products